data:extend({
    {
        type="item",
        name="small-hsv-lamp-item",
        stack_size=50,
        icon="__HSV-lamps__/graphics/icons/hsv-lamp-icon.png",
        icon_size=64,
        place_result="small-hsv-lamp"
    }
})