data:extend({
    {
        type="recipe",
        name="uranium-inserter-recipe",
        category="crafting-with-fluid",
        ingredients={
            {type="fluid",name="lubricant",amount=100},
            {name="speed-module-3",amount=4},
            {name="uranium-235",amount=5},
            {name="stack-inserter",amount=10},
            {name="iron-gear-wheel",amount=100}
        },
        enabled=false,
        subgroup="inserter",
        result_count=1,
        result="uranium-inserter-item"
    }
})