data:extend({
    {
        type="recipe",
        name="uranium-splitter-recipe",
        category="crafting-with-fluid",
        ingredients={
            {type="fluid",name="lubricant",amount=100},
            {name="processing-unit",amount=20},
            {name="uranium-235",amount=1},
            {name="iron-gear-wheel",amount=180},
            {name="express-splitter",amount=1}
        },
        enabled=false,
        subgroup="belt",
        result_count=1,
        result="uranium-splitter-item"
    }
})