data:extend({
    {
        type="recipe",
        name="uranium-belt-recipe",
        category="crafting-with-fluid",
        ingredients={
            {type="fluid",name="lubricant",amount=100},
            {name="speed-module-3",amount=2},
            {name="uranium-235",amount=1},
            {name="iron-gear-wheel",amount=100},
            {name="express-transport-belt",amount=10}
        },
        enabled=false,
        subgroup="belt",
        result_count=1,
        result="uranium-belt-item"
    }
})